# Generated by Django 3.1 on 2020-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201213_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=300)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='decks',
            old_name='timestamp',
            new_name='timeStamp',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
