# Generated by Django 3.1 on 2020-12-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201215_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Input', 'Input'), ('Translation', 'Translation'), ('multiple_translation', 'Multiple Translation')], max_length=20)),
            ],
        ),
    ]
