# Generated by Django 3.1 on 2021-01-30 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_error_related_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='error',
            name='type',
            field=models.CharField(choices=[('Input', 'Input'), ('Translation', 'Translation'), ('Multiple_Translation', 'Multiple Translation')], max_length=20),
        ),
    ]
