# Generated by Django 3.1 on 2020-12-13 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='word_list',
        ),
        migrations.AddField(
            model_name='decks',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decks',
            name='userToken',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='fields',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='userToken',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
