# Generated by Django 3.1 on 2020-12-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201213_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Correction',
        ),
    ]
